plugins {
     id 'com.android.application'
}

android {
    namespace 'neion.nlchr2'
    compileSdk = 37

    packagingOptions {
        exclude 'kotlin/**'
    }

    defaultConfig {
        applicationId "neion.nlchr2"
        minSdk 30
        targetSdk 37
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
